// Generated by generate-enums.ts — do not edit by hand.
// Each entry is a const object with a derived string-literal union type
// (same name for both). The type is structurally identical to the union
// OpenAPI produces from the corresponding t.UnionEnum schema, so values
// coming back from the server via the generated OpenAPI types assign
// cleanly to these types. Do not revert to `enum` syntax.
export const Collection = {
  address: 'address',
  annotation: 'annotation',
  compilation: 'compilation',
  contact: 'contact',
  digitalentity: 'digitalentity',
  entity: 'entity',
  institution: 'institution',
  person: 'person',
  physicalentity: 'physicalentity',
  tag: 'tag',
} as const;

export type Collection = (typeof Collection)[keyof typeof Collection];

export const isCollection = (value: unknown): value is Collection =>
  typeof value === 'string' && (Object.values(Collection) as string[]).includes(value);

export const EntityAccessRole = {
  owner: 'owner',
  editor: 'editor',
  viewer: 'viewer',
} as const;

export type EntityAccessRole = (typeof EntityAccessRole)[keyof typeof EntityAccessRole];

export const isEntityAccessRole = (value: unknown): value is EntityAccessRole =>
  typeof value === 'string' && (Object.values(EntityAccessRole) as string[]).includes(value);

export const ProfileType = {
  user: 'user',
  organization: 'organization',
} as const;

export type ProfileType = (typeof ProfileType)[keyof typeof ProfileType];

export const isProfileType = (value: unknown): value is ProfileType =>
  typeof value === 'string' && (Object.values(ProfileType) as string[]).includes(value);

export const UserRank = {
  uploader: 'uploader',
  admin: 'admin',
} as const;

export type UserRank = (typeof UserRank)[keyof typeof UserRank];

export const isUserRank = (value: unknown): value is UserRank =>
  typeof value === 'string' && (Object.values(UserRank) as string[]).includes(value);
