// Generate const-object enums with derived string-literal union types.
// Each entry is exported as both a runtime const (for iteration/validation)
// and a same-named type alias whose type is a pure string-literal union.
// This keeps the type structurally identical to the union OpenAPI generates
// from `t.UnionEnum` schemas, avoiding cross-package assignment errors
// (a TS `enum` does not match the string-literal union it corresponds to).
// Do not revert to `enum` syntax here.
import * as schemas from './schemas';

const HEADER = `// Generated by generate-enums.ts — do not edit by hand.
// Each entry is a const object with a derived string-literal union type
// (same name for both). The type is structurally identical to the union
// OpenAPI produces from the corresponding t.UnionEnum schema, so values
// coming back from the server via the generated OpenAPI types assign
// cleanly to these types. Do not revert to \`enum\` syntax.
`;

const generateEnums = async () => {
  const enumSchemas = Object.entries(schemas).filter(
    ([_, schema]) => typeof schema === 'object' && schema !== null && 'enum' in schema,
  );

  const generatedEnums: string[] = [];

  for (const [name, schema] of enumSchemas) {
    const enumValues = schema.enum;
    if (!Array.isArray(enumValues)) continue;
    const cleanName = name.replace('EnumSchema', '');
    const constDefinition = `export const ${cleanName} = {\n${enumValues.map((value: string) => `  ${value}: '${value}',`).join('\n')}\n} as const;`;
    const typeDefinition = `export type ${cleanName} = (typeof ${cleanName})[keyof typeof ${cleanName}];`;
    const typeguardDefinition = `export const is${cleanName} = (value: unknown): value is ${cleanName} =>\n  typeof value === 'string' && (Object.values(${cleanName}) as string[]).includes(value);`;
    generatedEnums.push([constDefinition, typeDefinition, typeguardDefinition].join('\n\n'));
  }

  await Bun.write('./enums.ts', HEADER + generatedEnums.join('\n\n') + '\n');
};

generateEnums()
  .then(() => {
    console.log('Enums generated successfully.');
  })
  .catch(error => {
    console.error('Error generating enums:', error);
  });
